### PR TITLE
Check the bundle header title and file name match

### PR DESCRIPTION
**Pull request by Gabib32**
Ensure that the bundle file name and the header title scraped
from the file are equal. Add a unit test to check this
functionality, and update other unittests that fail with
the new check.

Signed-off-by: gabrielle beyer <gabrielle.n.beyer@intel.com>

### CODE REVIEW

**Comment by matthewrsj** [comment]
Is this a required check?

**Comment by phmccarty** [comment]
I'm pretty sure mixer enforces this. Unless the mixer check was disabled?

**Comment by matthewrsj** [comment]
But should a mismatch here fail parsing of the file? I guess that's fine.

@Gabib32 you have a `make lint` error.

**Comment by phmccarty** [comment]
Ah, the mixer check was disabled a while back (https://github.com/clearlinux/mixer-tools/commit/009751357e)

**Comment by matthewrsj** [comment]
Ah yes, I remember arguing for it to be taken out then too ;)

**Comment by Gabib32** [comment]
Yeah, it will require some repeating of code though, like walking the bundles/ dir to get all bundle information and whatnot.

**Comment by matthewrsj** [comment]
Make it a helper function? One exists in mixer-tools for that purpose.

**Pull request closed without merging**
