### PR TITLE
Vendor required dependencies

### PR DESCRIPTION
**Pull request by tmarcu**
Signed-off-by: Tudor Marcu <tudor.marcu@intel.com>

### CODE REVIEW

**Comment by icarus-sparry** [comment]
Are you going to change the travis file to no longer load these vendored packages?

**Comment by matthewrsj** [comment]
So, I'm not exactly sure why this is failing, but you vendored `redigomock` when you shouldn't have since it is a test dependency.

**Comment by matthewrsj** [comment]
@tmarcu are you going to debug this or do we want to wait to see what go1.11/go modules look like?

**Comment by matthewrsj** [comment]
https://tip.golang.org/cmd/go/#hdr-Modules_and_vendoring

**Comment by tmarcu** [comment]
Maybe we should wait and see what the new options will be. I don't really want to debug that & if it's getting obsoleted might as well go with the newest.

**Comment by matthewrsj** [comment]
Right. Closing.

**Pull request closed without merging**
